#!/bin/bash
# use this to do a FULL backup to internal backup drive.
# fetch the linux version you are about to back up:
version=$(lsb_release -a | sed -n 's/Description:[\t]//p' | tr " " _)
destination="/media/Daten/Linux_Backup/"
sleep 1
echo "Detected Linux Version:"
echo $version
sleep 1
echo "PLEASE BE SURE TO START SCRIPT WITH SUDO COMMAND!"
echo "Starting Backup..." 
#echo "We'll begin with Thinderbird (separate folder, non compressed)"
sleep 1
#mkdir -p /media/Daten/Email-Backups/Thunderbird_current_Backup
#rsync -auv --log-file=/home/user/$(date +%Y%m%d)_rsync.log --progress /home/user/.thunderbird/ /media/Daten/Email-Backups/Thunderbird_current_Backup
#echo "Thunderbird backup finished. Now starting to backup Home Folder"
#sleep 1
echo "Backing up home folder of current Linux distribution"
sleep 1
mkdir -p $destination
7za u -mmt=3 $destination$version.7z -r /home/
echo "Backed up your home folder of Linux. This can become important when installing a new release of Linux Mint (personal settings)"
sleep 1
echo "Now backing up your etc-settings (all of them...thats why we are now encrypting)"
sleep 1
7za u -p -mmt=3 $destination$version.7z -r /etc/
echo "Backed up your etc folder of Linux. This can become important when installing a new release of Linux Mint (some program settings)"
sleep 1
echo "Making a list of all of the programs you have installed with package manager"
sleep 1
mkdir -p /Installed_Programs
dpkg --list | grep -v -e '-dev' -e 'ii  lib' >/Installed_Programs/packages.txt
echo "Making a list of all of the programs you have installed from source or binaries"
sleep 1
ls -1 /opt >/Installed_Programs/binary_packages.txt
ls -1 /usr/local/bin >/Installed_Programs/source_packages.txt
echo "Getting your Repro Key (public key)"
sleep 1
apt-key exportall > /Installed_Programs/Repo.keys
echo "Adding new files to zip"
sleep 1
7za u -mmt=3 $destination$version.7z -r /Installed_Programs/
echo "Backup script has finished. Have a nice day."
read -p "Press any key to continue... " -n1 -s

################################################################################################################
################################################################################################################
#echo "backing up the Daten drive to the Backup drive"
#rsync -auv --log-file=/home/user/$(date +%Y%m%d)_rsync.log --progress /media/Daten/ /media/Backup
#echo "Backup script has finished. Have a nice day."
#read -p "Press any key to continue... " -n1 -s


